AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'public/**/*'
    - 'node_modules/**/*'
    - 'app/assets/images/**/*'
    - 'bin/**/*'
Style/SymbolArray:
  Enabled: false
Rails/Blank:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
    Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
# until parser does not bork on <<~
Layout/IndentHeredoc:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/SpaceInsideBrackets:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/VariableName:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Max: 18
Metrics/CyclomaticComplexity:
  Max: 7
Metrics/ModuleLength:
  Enabled: false
Style/FileName:
  Enabled: false
